name: app

type: php:8.1

dependencies:
    php:
        composer/composer: "^2"

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        - pdo_pgsql

relationships:
    # DATABASE_URLq
    database: 'database:postgresql'

#variables:
#    php:
#        # uncomment on PHP 7.4+
#        #opcache.preload: config/preload.php

build:
    flavor: none

disk: 512

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"
            rules:
              '^\/assets\/.*':
                expires: 365d


mounts:
    "/var": { source: local, source_path: var }
    

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | bash
        
        NODE_VERSION=18 symfony-build
        
        curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.3.2/tailwindcss-linux-x64
        mv tailwindcss-linux-x64 bin/tailwindcss
        chmod +x bin/tailwindcss
        ./bin/tailwindcss -i assets/styles/app.css -o assets/styles/app.tailwind.css
        
        php bin/console asset-map:compile

    deploy: |
        set -x -e

        symfony-deploy
